info:
  name: teambuiltingusers
  description: Team Builting Users, to manage the users

server:
  port: ${PORT:8090}

---

# Queue configuration
messaging:
  amqp:
    team:
      exchange:
        name: teambuilting.ex.team
        durable: true
      queue:
        name: teambuilting.q.team
        binding: team.#
    player:
      exchange:
        name: teambuilting.ex.player
        durable: true
      queue:
        name: teambuilting.q.player
        binding: player.#


resources:
  token: oauth/token
  users: api/v2/users

---

spring:
  profiles: production

---

endpoints:
  enabled: true # Enable endpoints.
  actuator.enabled: true # Enable the endpoint.

---

auth0:
  domain: manuelarte.eu.auth0.com
  issuer: https://manuelarte.eu.auth0.com/
  clientId: XOBz4RdzWoMnpxAvXKtK9R8W9IODYKsl
  clientSecret: tvKvKZd1tigVIAGztcOELwKIj0B0DswEbLdRG1PWu7NfZXk6VGbGkWdQjFpTZmWp
  securedRoute: NOT_USED
  base64EncodedSecret: true
  authorityStrategy: ROLES
  defaultAuth0ApiSecurityEnabled: false
  signingAlgorithm: HS256
  #signingAlgorithm: RS256
  #publicKeyPath: certificate/cert.pem